### ISSUE TITLE
Refine Property Tax Credit Rebate rules so that we do not return rebate in results if a HH member is under 18 and disabled

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#129]
Context: This rebate is available to someone with disabilities so long as, among other things, they cannot be declared as a dependent on someone else's tax return; we had 1-2 ARC screeners where the rebate was returned as a result even though the person with the disability was a child who would be a dependent for tax purposes - we should get close with accuracy if we use age as a proxy for being a tax dependent.

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena Looks good in sample testing.
