### ISSUE TITLE
As a user, if I select SSI and/or SSDI as an income source, I would like the benefit(s) to be excluded from the results even if I do not select it as a current benefit in Step 9

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#131]

**Comment by kbottagaro** [comment]
@sydney-devine This function is working, and those items are excluded from both my benefits results and benefits I'm ineligible for. I think this is ok, but I wonder if we'll get feedback on this. I'm inclined to leave as-is and then revisit if someone were to raise this as a question. Thoughts?

**Comment by sydney-devine** [comment]
I think leave as is.

**Comment by kbottagaro** [comment]
ok, thanks

**Comment by egberts** [comment]
IANAL but this one is:

https://www.disabilitysecrets.com/resources/social-security-disability/ssdi/income-limits-ssdi-benefits

**Comment by kbottagaro** [comment]
Could you please clarify? The point of this ticket was that someone might list one of these programs as income but fail to check that it’s a current benefit - but by virtue of the fact that they’re marking it as an income source, they have the benefit and shouldn’t see it in results. 

That said, @CalebPena I ran a test to review this comment. I indicated I receive SSI both as income and in step 8, and SSI still showed up in results. Test here - https://screener.myfriendben.org/8967bbf6-c69b-4731-9304-5da13b226a36/results/benefits

And in this test, https://screener.myfriendben.org/c6eec3ef-ee7d-483a-8273-7f2ca10b0903/results/benefits, I marked SSDI as income and still got it in results. 

So I’m thinking we may need to reopen this ticket to fix this. The point is that if someone reports SSI as income and/or in step 8, SSI shouldn't show up in results. And if someone reports SSDI as income and/or in step 8, SSDI shouldn't show up in results.

**Comment by sydney-devine** [comment]
> Could you please clarify? The point of this ticket was that someone might list one of these programs as income but fail to check that it’s a current benefit - but by virtue of the fact that they’re marking it as an income source, they have the benefit and shouldn’t see it in results.
> 
> That said, @CalebPena I ran a test to review this comment. I indicated I receive SSI both as income and in step 8, and SSI still showed up in results. Test here - https://screener.myfriendben.org/8967bbf6-c69b-4731-9304-5da13b226a36/results/benefits
> 
> And in this test, https://screener.myfriendben.org/c6eec3ef-ee7d-483a-8273-7f2ca10b0903/results/benefits, I marked SSDI as income and still got it in results.
> 
> So I’m thinking we may need to reopen this ticket to fix this. The point is that if someone reports SSI as income and/or in step 8, SSI shouldn't show up in results. And if someone reports SSDI as income and/or in step 8, SSDI shouldn't show up in results.

This already got done.

**Comment by kbottagaro** [comment]
I was responding to the comment someone made in the ticket. But in trying
to understand the comment, I ran a couple of tests, and I think there's a
bug. SSI and SSDI are coming up in results even if someone marks those as
income and/or a benefit they already receive.
