### ISSUE TITLE
Refine assumption sent to Policy Engine re: dependents

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#133]
Update assumptions sent to Policy Engine so that HH members over 18 without disabilities will not be counted as dependents. [context: Policy Engine is adding a $500 credit for other dependents to the child tax credit calculations - so CTC results are being overstated in HHs with multiple adults]

**Comment by kbottagaro** [comment]
@sydney-devine This looks good in staging.
