### ISSUE TITLE
Add Nurse-Family Partnership as new benefit

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#137]
Row 2 of this spreadsheet

**Comment by CalebPena** [comment]
@sydney-devine you did not link the spreadsheet.

**Comment by CalebPena** [comment]
@sydney-devine, @kbottagaro says that this is not ready yet.

**Comment by sydney-devine** [comment]
@CalebPena moving back to backlog. My bad!

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena Updating this ticket to connect it to this one - https://app.zenhub.com/workspaces/myfriendben-652eb93b7dc40e0935103f4c/issues/gh/gary-community-ventures/benefits-calculator/1042 - that involves adding a text option for estimated savings.

**Comment by sydney-devine** [comment]
@kbottagaro need the spreadsheet for this one of what Caleb needs to pull for eligibility criteria

**Comment by kbottagaro** [comment]
The sheet is here - https://docs.google.com/spreadsheets/d/124rIILFV_BLBGuqvkAd9f3O0NV2VxZzLNWiF8eAS42c/edit#gid=429275458. But note I'm still waiting for final sign-off from the NFP team on our suggestion re: value.
