### ISSUE TITLE
As an administrator, I would like the ability to add/remove referral sources to the backend

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#141]
This should include adding/removing the referral source, and adding in a logo for white label.

**Comment by sydney-devine** [comment]
HOLD for regional config backend piece to be ready.

**Comment by CalebPena** [comment]
We can add this to the regional config. We also need to parse these into formatted messages on the frontend.

**Comment by sydney-devine** [comment]
Closing - duped
