### ISSUE TITLE
As an administrator, I would like to assign navigators to benefits with a zip code filter/sorting function

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#142]
Want to **add DPP as a UPK navigator for Denver only**. I can add DPP as a navigator after the zip code filter is created. 

The UPK Helpline is currently listed as the UPK navigator statewide. Would also like to be able to **use only DPP, and not the UPK Helpline, in Denver**.

**Comment by CalebPena** [comment]
@sydney-devine Duplicate of #186

**Comment by sydney-devine** [comment]
@CalebPena closing
