### ISSUE TITLE
Translation Fix: Language under apply with assistance buttons

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#154]
"Link" and "Phone number" under "Apply with Assistance" are in English in all languages and should be translated into the applicable language. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb557f571f91ffd316e9b6bf8e5ca004b16dc82f/image.png)

**Comment by kbottagaro** [comment]
I believe we're going to keep Benefits in Action's name in French, but it's translating as "Les avantages en action." Looks ok in Amharic based on Google Translate.

Also, assume this is because we're in staging, but I don't see Colorado Shines as CCCAP assister.
