### ISSUE TITLE
Update NSLP Value

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#155]
Update value for NSLP now that Colorado has universal free meals. We override Policy Engine's value. KB will come up with new value, and we'll need to input it in the backend.

**Comment by sydney-devine** [comment]
@kbottagaro - do you have updated values for this?

**Comment by kbottagaro** [comment]
No - it's on my list, and I haven't forgotten, but other priorities have
bumped it. Will get to it.

**Comment by sydney-devine** [comment]
@kbottagaro do you have values for this?

**Comment by kbottagaro** [comment]
@sydney-devine Was already done - https://app.zenhub.com/workspaces/myfriendben-652eb93b7dc40e0935103f4c/issues/gh/gary-community-ventures/benefits-api/198. Was working when we did releases, not sure what happened.
