### ISSUE TITLE
Clean up API endpoints for old conditions we no longer use (deactivate?)

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#158]

**Comment by ivonne-hernandez** [comment]
@CalebPena Can you also update the Swagger Docs when you work on this ticket?

**Comment by CalebPena** [comment]
Need to update the screen `Serializer` so that those programs are removed.

**Comment by ivonne-hernandez** [comment]
Remove it in serializer not the model
