### ISSUE TITLE
Let's Get Set White Label - Only return benefits we are comfortable returning until individual gives additional information

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#160]
Need ability to turn on/off benefits
KB to make recommendation on 11/15
Present to Clare immediately thereafter

**Comment by sydney-devine** [comment]
https://docs.google.com/spreadsheets/d/1jYlm4kD5yFHitlSXOpgpDJ91J1rJGwrc7dLUhw3cF9Y/edit#gid=369693103

**Comment by kbottagaro** [comment]
@sydney-devine i meant to ask - do we estimate this will be released on January 5?  Wondering when we'll be able to share with LGS team.  Thanks! - Rebecca
