### ISSUE TITLE
Add Sentry to handled API errors

### ISSUE THREAD

**Issue by civicpixel** [Gary-Community-Ventures/benefits-api#173]
https://docs.sentry.io/product/sentry-basics/integrate-backend/capturing-errors/ -- this will allow us to catch any issues for saving users who signup for updates.

**Comment by CalebPena** [comment]
I think we want to do this:
https://docs.sentry.io/platforms/python/integrations/django/http_errors/?original_referrer=https%3A%2F%2Fwww.google.com%2F

**Comment by sydney-devine** [comment]
@CalebPena Closing this since we already released it.

**Comment by CalebPena** [comment]
I think this was for logging other errors that were not being caught by Sentry right now.
