### ISSUE TITLE
Make Default Insurance for Each Member

### ISSUE THREAD

**Issue by CalebPena** [Gary-Community-Ventures/benefits-api#175]
Attach a default insurance for each member where "don't know" is the insurance that the members have.

**Comment by sydney-devine** [comment]
@CalebPena - can it default to No insurance? Otherwise, we probably shouldn't just assume they have something else.

**Comment by CalebPena** [comment]
I was planning on assuming 'Don't Know'

**Comment by sydney-devine** [comment]
@CalebPena is it not doing that right now when someone clicks Don't Know?
