### ISSUE TITLE
Create new django app for managing regional configuration

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#178]

**Comment by CalebPena** [comment]
# Instructions

- [ ] Create new app by running `python manage.py startapp configuration`
- [ ] In `configuration/models` create a new `Configuration` [model](https://docs.djangoproject.com/en/4.2/topics/db/models/) with the following fields
    - [ ] Name: should be a [CharField](https://docs.djangoproject.com/en/4.2/ref/models/fields/#charfield)
    - [ ] Data: should be a [JSONField](https://docs.djangoproject.com/en/4.2/ref/models/fields/#jsonfield)
    - [ ] Active: should be a [BooleanField](https://docs.djangoproject.com/en/4.2/ref/models/fields/#booleanfield)
    - [ ] Add `__str__` method that returns `self.name`
- [ ] [Make migrations](https://docs.djangoproject.com/en/4.2/topics/migrations/#workflow)
    - [ ] Run `python manage.py makemigrations`
    - [ ] Run `python manage.py migrate`
- [ ] [Add model to admin](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/#modeladmin-objects)
    - [ ] In `configuation/admin` create a `ConfigurationAdmin` class with `name` as the [search field](https://docs.djangoproject.com/en/4.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_fields)
    - [ ] Register the `Configuration` model and `ConfigurationAdmin` (example in `programs/admin`)
- [ ] Test by going to http://localhost:8000/admin/configuration/configuration/ and trying to add a new object
- [ ] Create a `ConfigurationSerializer`
    - [ ] Add a `serializers.py` file in the `configuration` app
    - [ ] Create a [serializer](https://www.django-rest-framework.org/api-guide/serializers/#modelserializer) for the `Configuration` model (example in `screener/serializers`)
        - [ ] Add `model = Configuration` to  `Meta` class
        - [ ] Add `fields = '__all__'` to `Meta` class
- [ ] Create a [read only model view](https://www.django-rest-framework.org/api-guide/viewsets/#readonlymodelviewset)
    - [ ] In the `configuration/views` file create a `ConfigurationView`
    - [ ] Make the `queryset = Configuration.objects.filter(active=True)`
    - [ ] Make the serializer the `ConfigurationSerializer`
    - [ ] Add `permission_classes = [permissions.DjangoModelPermissions]`
    - [ ] Add a [retrieve method](https://www.django-rest-framework.org/api-guide/viewsets/#viewset-actions) (example on line 55 of `screener/views`)
        - [ ] Get the object where `name` is equal to `pk`
        - [ ] Serialize object and return response
- [ ] Add view to [urls](https://www.django-rest-framework.org/tutorial/quickstart/#urls)
    - [ ] Add `api/` route to `benefits/urls` that includes `configuration.urls`
    - [ ] Register route with name `configuration` and the `ConfigurationView` (example in `screener/urls`)
- [ ] Test
    - [ ] Add new configuration object in http://localhost:8000/admin/configuration/configuration/
    - [ ] Go to http://localhost:8000/api/configuration/
    - [ ] Go to http://localhost:8000/api/configuration/[name_of_object_created]/

## Explanation

- Create new app: Django allows each website to have multiple apps. Each app should hold routes, views, and models that do one thing. For example, in MFB, we have separate apps for the screener, the programs, and translations.
- Models: Django provides tooling for SQL in the form of models. The Model class defines how a SQL table is created in PostgreSQL, and you run `makemigrations` to create the instructions to update the table (stored in the `migrations` directory), and `migrate` to update the table. Additionally, Django provides an easy syntax when working with models so you don't have to write raw SQL.
- Admin: Django provides an out of the box admin interface for updating your model objects (each row in an SQL table is turned into an object in Django).
- Serializers: Django Rest Framework (DRF) is a library that goes on top of Django that provides REST endpoints. A serializer tells DRF how to turn an object into a JSON (or XML or Whatever other protocol) response.
- Views: Views are code the runs when a route is accessed. DRF provides an abstraction that can create a view based on a model and a serializer. The view that we are using provides a list route, and a retrieve route which lets you fetch all of the active configuration, or lets you fetch a configuration by name.
- Urls: The urls tell Django which view to execute based on the API route.

**Comment by sydney-devine** [comment]
@bespinosa01 & @myang1010 - here are Caleb's notes for your guys' review before you guys meet and review stuff for the backend. 

@rickyctd FYI
