### ISSUE TITLE
Add function to assign assisters based on county

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#186]
This relates to the ticket that adds the Weatherization Assistance Program (WAP) to MFB and should be completed at the same time #187 

See Column M of this sheet (https://docs.google.com/spreadsheets/d/1OreJkSgFaUeamFSvk7Ww0Sh43BK77Ccc-KScyApc0m4/edit#gid=933204121) for county-specific assisters for WAP.

**Comment by sydney-devine** [comment]
@CalebPena - Did we say things like this for assigning based on county is easier to just be hard coded in vs building out the functionality? I feel like this has come up before.

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena Circling back on Sydney's question above since I'm anticipating Weatherization Assistance Program may go live with next release or so.

**Comment by CalebPena** [comment]
Add a county model and then add select on the counties.

or 

Add functionality to add functions to specific navigators like the urgent needs.

**Comment by sydney-devine** [comment]
How to use documentation
https://docs.google.com/document/d/14DFCBcib4NJ_YYJf7JLRqYz4mRjyQB0LpeoVgxsPne4/edit
