### ISSUE TITLE
Add Weatherization Assistance Program to MFB

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#187]
Add Weatherization Assistance Program to MFB. Details are in this sheet - https://docs.google.com/spreadsheets/d/1OreJkSgFaUeamFSvk7Ww0Sh43BK77Ccc-KScyApc0m4/edit?usp=sharing.

Notes:
- When this benefit is added, we'll deactivate Energy Resource Center.
- This should be linked to a ticket that lets us choose assisters by county, as WAP assisters work in designated counties. See this ticket - https://app.zenhub.com/workspaces/myfriendben-652eb93b7dc40e0935103f4c/issues/gh/gary-community-ventures/benefits-calculator/780.

**Comment by kbottagaro** [comment]
@sydney-devine I created a related ticket to update Step 8. That ticket is here - https://app.zenhub.com/workspaces/myfriendben-652eb93b7dc40e0935103f4c/issues/gh/gary-community-ventures/benefits-calculator/805

**Comment by kbottagaro** [comment]
@CalebPena I want to add this to the database so it's ready to activate when it's added on the backend. What will its short name be?

**Comment by sydney-devine** [comment]
@kbottagaro - Adding to this current sprint. We can circle back when it's ready to be tested for short name.

**Comment by kbottagaro** [comment]
Tested with a sample of family sizes, income levels, and counties, and this looks good.
