### ISSUE TITLE
Update SSDI income limits and values for 2024

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#197]
Effective January 1, 2024: 
- Change monthly earned income limit for people with non-blind disabilities from $1470 to $1550
- Change monthly earned income limit for people who are blind from $2460 to $2590
- Change SSDI benefit values from $1364/month to $1537/month
- Change substantial gainful activity values (i.e., maximum monthly earnings someone may get and still qualify for SSDI) from (1)  $1470 to $1550 for disabled individuals and (2) $2460 to $2590 for blind individuals

Source is here - https://www.ssa.gov/news/press/factsheets/colafacts2024.pdf

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena Ran a few tests with different variables, and appears to be good.

**Comment by egberts** [comment]
It gets complicated...

https://www.disabilitysecrets.com/resources/social-security-disability/ssdi/income-limits-ssdi-benefits
