### ISSUE TITLE
Update 2024 FPL

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#218]
Update FPL for select programs that update their FPL in January, as noted in this sheet - https://docs.google.com/spreadsheets/d/1lXxSv4Z4hiZJpsdg6j_rQzICOxEHeImelu7VY8yyRAw/edit?usp=sharing.

**Comment by CalebPena** [comment]
This has been updated in Django admin. It is already live.

**Comment by sydney-devine** [comment]
@CalebPena closing out issue.
