### ISSUE TITLE
2024 update eligibility for PTC Rebate 

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#229]
CO Specific:

Update the income limits for the Property Tax Credit rebate - $18,026 for single filers and $23,345 for married filers.

https://tax.colorado.gov/PTC-rebate

**Comment by CalebPena** [comment]
This file: https://github.com/Gary-Community-Ventures/benefits-api/blob/main/programs/programs/property_credit_rebate/calculator.py

**Comment by kbottagaro** [comment]
@CalebPena Testing with single person at income levels below $18,026 and not receiving PTC at all income levels I'm testing - e.g., 1-person HHs with annual income = $17,400 and $18,000 not getting benefit

**Comment by kbottagaro** [comment]
@CalebPena Testing with single person at income levels below $18,026 and not receiving PTC at all income levels I'm testing - e.g., 1-person HHs with annual income = $17,400 and $18,000 not getting benefit

**Comment by kbottagaro** [comment]
@CalebPena Testing a couple with annual income = $23,340 and didn't get PTC in results.

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena Updated income limits are now working.
