### ISSUE TITLE
Move components off of frontend and into the new django admin regional config backend

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#267]
- Step-8 categories
- Step-8 programs
- Urgent need options (Can only update text or remove)
- Counties in zip code
- Zip options
- Referrer sources options

**Comment by CalebPena** [comment]
We want to move these options to the backend, so that they can be changes in Django.

1. Add the config to the backend.
2. Update the config type.
3. Use the [config](https://github.com/Gary-Community-Ventures/benefits-calculator/pull/906) instead of the static files.

Example:
```
const {config} = useContext(Context);
config.zipcodes
```

**Comment by mexi-cano** [comment]
Is this more of a front-end ticket? Seems like the backend work will be just adding the config data for testing.

**Comment by mexi-cano** [comment]
I have moved the `countiesByZipcode` to the backend. It looks like the `questions` object utilizes the zipcodes which are now available through Context. I believe we can only access the Context API within a function component so I am unsure about how to best make the zipcode data available to the `questions` object. Could you share any guidance on a preferred approach? Thanks! @CalebPena @ivonne-hernandez 

<img width="1058" alt="Screenshot 2024-03-01 at 3 17 44 PM" src="https://github.com/Gary-Community-Ventures/benefits-api/assets/7133950/491d633e-627f-4d52-838e-6e9407855fe3">
<img width="437" alt="Screenshot 2024-03-01 at 3 17 33 PM" src="https://github.com/Gary-Community-Ventures/benefits-api/assets/7133950/544539a4-2192-4a73-917e-4df3c7f1feac">
<img width="1285" alt="Screenshot 2024-03-01 at 3 16 46 PM" src="https://github.com/Gary-Community-Ventures/benefits-api/assets/7133950/cc21b1f2-9927-4532-a288-821f637edcd6">

**Comment by CalebPena** [comment]
@mexi-cano In the `FollowUpQuestions` component, there is an if statement on line 59 that already has additional logic for the county select. You can use the config there, and remove it from where it is now.
