### ISSUE TITLE
Allow regional config to handle translatable fields

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#268]

**Comment by CalebPena** [comment]
Some of our current config files have formatted messages, that can not be represented with JSON. We need a way to represent our translations in JSON, and then use that to create a `FormattedMessage`.

One option is to represent translations as an object with a `label` and a `default_message`. We could then loop through and see if the JSON has a `label` or `default_message` and then replace that with a `FormattedMessage`.

Example:
```
{
  message: {_label: "hello", _default_message: "world"}
}
```
Turns into:
```
{
  message: <FormattedMessage id="hello" defaultMessage="world" />
}
 ```

**Comment by myang1010** [comment]
Hi @CalebPena ,  just want to make sure my understanding about this ticket is right. So our current `config files` data is in this original format, 
```
{
  message: {_label: "hello", _default_message: "world"}
}
```
And we want them to be in this transformed format, 

```
{
  message: <FormattedMessage id="hello" defaultMessage="world" />
}
```
Do you have an example of those config files? Am I suppose to write a script to transform config files with original data format to the transformed format? Or where does the change should happen? Thanks.

**Comment by CalebPena** [comment]
The config is something that is entered into Django admin. We currently don't have any test data, but you can add some by going to http://localhost:8000/admin/configuration/configuration/.

FYI, this should also handle nested fields:
```
{
  nested: {
    message: {_label: "hello", _default_message: "world"}
  }
}
```
```
{
  nested: {
    message: <FormattedMessage id="hello" defaultMessage="world" />
  }
}
```
