### ISSUE TITLE
Update OmniSalud value

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#297]
For OmniSalud, update value to show $610 / person.

**Comment by sydney-devine** [comment]
@kbottagaro - currently we have dif values for children, seniors & adults. Should they all be changed to this value?

**Comment by sydney-devine** [comment]
@kbottagaro and will you please clarify if it's $610 per year?

**Comment by kbottagaro** [comment]
For OmniSalud? I didn't think we had age-based values for that one.

**Comment by kbottagaro** [comment]
Sorry - it's $610/person/month.

**Comment by kbottagaro** [comment]
@CalebPena Looks good.
