### ISSUE TITLE
Add Foreclosure Financial Assistance Program to near-term needs resources

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#298]
Add Foreclosure Financial Assistance Program to near-term needs resources. NOTE that this is available only to Denver residents whose income doesn't exceed 80% AMI. Program details are in this sheet - https://docs.google.com/spreadsheets/d/1pN_WoGkaOLGlNlHmGVwNeOJvlW86X8fj_D3WQVyg_Is/edit#gid=141622965 - which links to a sheet with income levels (same as TRUA income levels).

**Comment by ivonne-hernandez** [comment]
Look at TRUA for guidance.
