### ISSUE TITLE
Update OAP grant standard for 2024

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#306]
Update OAP grant standard to $982 for 2024 (currently $952). 

Source: https://sos.state.co.us/CCR/GenerateRulePdf.do?ruleVersionId=11264&fileName=9%20CCR%202503-5

**Comment by CalebPena** [comment]
https://github.com/PolicyEngine/policyengine-us/pull/4402

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena This looks good.
