### ISSUE TITLE
Check if a user can submit just a phone number when signing up for notifications

### ISSUE THREAD

**Issue by CalebPena** [Gary-Community-Ventures/benefits-api#309]
Got a couple Sentry issues where phone only requests were failing.

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena I am unable to add only a phone number.

**Comment by CalebPena** [comment]
@kbottagaro Did you enter a valid phone number?

**Comment by kbottagaro** [comment]
Yes - I used my cell number and am still prompted to also provide an email
address.
