### ISSUE TITLE
Frontend - Standalone page for list of current Colorado Benefits

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-api#366]
![Current List of Benefits Page](https://github.com/Gary-Community-Ventures/benefits-api/assets/109622199/352df2f9-7c1a-4756-bae6-8e68bdde21ec)

**Comment by kbottagaro** [comment]
@sydney-devine Caleb shared this ticket with me, and I have input website descriptions for each benefit - so this is ready to go on my end.
