### ISSUE TITLE
Use translated privacy policy and consent to contact links.

### ISSUE THREAD

**Issue by CalebPena** [Gary-Community-Ventures/benefits-api#396]
Move links to config. 

Some of the privacy policy and consent to contact links are hard coded right now. For the languages that have a translated privacy policy and consent to contact, we should link to the translated page instead.

Consent to Contact:

- https://co.myfriendben.org/es/additional-terms-and-consent-to-contact
- https://co.myfriendben.org/fr/additional-terms-and-consent-to-contact
- https://co.myfriendben.org/vi/additional-terms-and-consent-to-contact

Privacy Policy
- https://co.myfriendben.org/es/data-privacy-policy
- https://co.myfriendben.org/fr/data-privacy-policy
- https://co.myfriendben.org/vi/data-privacy-policy

**Comment by sydney-devine** [comment]
@CalebPena we only have for Spanish & Viet right now.

**Comment by CalebPena** [comment]
> @CalebPena we only have for Spanish & Viet right now.

For some of the links, we have it hard coded for English.

**Comment by sydney-devine** [comment]
> > @CalebPena we only have for Spanish & Viet right now.
> 
> For some of the links, we have it hard coded for English.

SorryI think I missed this. Right but the privacy policy is only done in Spanish and Viet. Everything is coded for English right?

**Comment by CalebPena** [comment]
On the landing page, both the privacy and consent to contact have en, es, vi, and fr, but on the sign up page the privacy has en, es, and vi, and the consent to contact has en.

**Comment by sydney-devine** [comment]
> On the landing page, both the privacy and consent to contact have en, es, vi, and fr, but on the sign up page the privacy has en, es, and vi, and the consent to contact has en.

We didn't get the consent to contact one translated. It's only in English right now. I'll need to talk to legal to see if it matters how we go about translating it.

**Comment by CalebPena** [comment]
> > On the landing page, both the privacy and consent to contact have en, es, vi, and fr, but on the sign up page the privacy has en, es, and vi, and the consent to contact has en.
> 
> We didn't get the consent to contact one translated. It's only in English right now. I'll need to talk to legal to see if it matters how we go about translating it.
> 
> Also, it's prob going to be jsut English/Spanish once we update the site.

It has French on the landing page: https://co.myfriendben.org/fr/additional-terms-and-consent-to-contact

**Comment by sydney-devine** [comment]
> > > On the landing page, both the privacy and consent to contact have en, es, vi, and fr, but on the sign up page the privacy has en, es, and vi, and the consent to contact has en.
> > 
> > 
> > We didn't get the consent to contact one translated. It's only in English right now. I'll need to talk to legal to see if it matters how we go about translating it.
> > Also, it's prob going to be jsut English/Spanish once we update the site.
> 
> It has French on the landing page: https://co.myfriendben.org/fr/additional-terms-and-consent-to-contact

OH just kidding.  . . I keep forgetting what I did on that site.
