### ISSUE TITLE
Update federal and Colorado child tax credit rules

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#412]
Make these changes to the child tax credit:

- Federal: The $500 Credit for Other Dependents is currently incorporated into the federal CTC. Update MFB to make this $500 credit its own benefit called Credit for Other Dependents. This will show up for HHs with dependents who are too old to qualify for the federal CTC.  

- Colorado: Show the Colorado child tax credit to eligible HHs only for children under 6 (0 through 5).

**Comment by CalebPena** [comment]
Per my conversation with Max, the non-refundable part of the CTC and the ODC are phased out together. Therefor, if we split them, we need to determine how to also split the phase out between the 2 programs.

**Comment by sydney-devine** [comment]
> Per my conversation with Max, the non-refundable part of the CTC and the ODC are phased out together. Therefor, if we split them, we need to determine how to also split the phase out between the 2 programs.

@kbottagaro ^ for when you're back.

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena Per my conversation with Caleb, we are going to keep the federal CTC and ODC together in Policy Engine. This ticket is now limited to fixing the issue where a user gets COCTC in results even though their dependents are too old to qualify for COCTC (because the COCTC is calculated as a % of the combined federal CTC/ODC). Suggestion: We change the name of the federal "Child Tax Credit" in results to read "Child Tax Credit / Credit for Other Dependents." This will be less confusing for users who may see the federal credit in results for an adult dependent in the HH. Can we do that under this ticket, or should I create a new ticket? I can update results language accordingly.
