### ISSUE TITLE
Adjust income eligibility calculations for Family Planning Limited Medicaid

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#420]
Adjust income eligibility calculations for Family Planning Limited Medicaid:
- Add a 5% income disregard for Family Planning Limited Medicaid. This effectively brings the max FPL to 265%, not 260%. If HH income exceeds the applicable FPL, the 5% disregard is applied to determine eligibility.
- Count each eligible person as 2 for purposes of determining HH size and applying applicable FPL. 

Sources for 5% disregard:
- 6/11/24 emailed confirmation from HCPF.
- Section 8.100.4.D of the regs (p. 57) at https://www.sos.state.co.us/CCR/GenerateRulePdf.do?ruleVersionId=11143: _An income disregard equivalent to five percentage points of the Federal Poverty Level for the applicable family size will be subtracted from MAGI-based income. . . . If an individual's MAGI-based countable income is above the income threshold for [the program] . . . the five percent (5%) disregard will be applied . . . as the last step to determine eligibility._
- KFF table shows Colorado at 265% with disregard for family planning - see https://files.kff.org/attachment/Table-2-Medicaid-and-CHIP-Eligibility-Enrollment-and-Renewal-Policies-as-States-Prepare-for-the-Unwinding-of-the-Pandemic-Era-Continuous-Enrollment-Provision.pdf

Sources for counting each eligible person as 2:
- HCPF June 2022 policy memo at https://hcpf.colorado.gov/sites/hcpf/files/HCPF%20PM%2022-004%20Medical%20Assistance%20New%20Limited%20Family%20Planning%20Services%20Income%20Expansion.pdf: For family planning, count each individual who may be eligible as 2 individuals (same methodology as if pregnant, but pregnant people aren't eligible for this program) and add all other members who would be included as part of MAGI HH. EXAMPLE:  Suppose you have a HH with mom, dad, and 2 kids, all requesting help. Mom and Dad’s tax filing status is married filing jointly, claiming both kids as dependents, with HH income at 200% FPL. The 2 kids qualify for CHP+ and will have a HH size of 4. Parents are over income for other programs but fall within family planning guidelines. Parent’s HH size is 6 (Mom = 2, Dad = 2, each child = 1).

**Comment by kbottagaro** [comment]
@sydney-devine Would like to get this ticket completed sooner rather than later. Caleb thought it could probably get worked into next week's releases.

**Comment by sydney-devine** [comment]
> @sydney-devine Would like to get this ticket completed sooner rather than later. Caleb thought it could probably get worked into next week's releases.

Yes I will tee it up for next week.

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena Looks good - ran through a few different scenarios.
