### ISSUE TITLE
add Nurturing Futures (Boulder County) direct cash assistance program to MFB

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#466]
Add Nurturing Futures to MFB as a primary benefit.

- Program is called Nurturing Futures.
- This is a Cash Assistance benefit.
- Eligibility requirements: (1) Boulder County resident; (2) head of HH is 18 or older; (3) HH includes at least one child under 4 (e.g., 0 through 3); (4) HH income is under 30% AMI (see chart at https://bouldercounty.gov/families/financial/nurturing-futures/#accordion1_9874437b54-46f1666b-a5e2b0a5-b10e - I'll put income into a spreadsheet we can pull from).

-

**Comment by kbottagaro** [comment]
NOTE: This program will be available only between August 6, 2024 and August 27, 2024.

**Comment by sydney-devine** [comment]
> NOTE: This program will be available only between August 6, 2024 and August 27, 2024.

@kbottagaro yea, you can just deactivate it once it's over.

**Comment by CalebPena** [comment]
@kbottagaro what is the value for this program?

**Comment by sydney-devine** [comment]
> @kbottagaro what is the value for this program?

$300/month for 2 years - to 725 families

**Comment by kbottagaro** [comment]
@Caleb Peña ***@***.***> Value will be $300/month or
$3600/year.

**Comment by kbottagaro** [comment]
@CalebPena You can use income in this sheet to calculate 30% AMI in order to determine eligibility - https://docs.google.com/spreadsheets/d/1PRpQ76Xa9Ru0U9MiwgYY5Yfl923lFz4Uu8a4g6A5N6Q/edit?usp=sharing.

**Comment by kbottagaro** [comment]
@sydney-devine @CalebPena This was previously tested and added.
