### ISSUE TITLE
Modify specific Pell Grant eligibility factors

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#470]
Modify the following Pell Grant eligibility parameters (refer to Pell guide at https://fsapartners.ed.gov/sites/default/files/2024-01/20242025FAFSAPellEligibilityandSAIGuide.pdf):

- For HHs with dependent students: update income protection allowance from $7,040 to $11,130 (p. 8 of guide)
- Exclude assets from calcluations under following scenarios (Appendix E starting on p. 38 of guide; note that guide references 2022 AGI for these purposes, but MFB will use current income reported by HH - this is different than applying 2022 FPL to determine eligibility for Max Pell or non-SAI Pell):
-----Dependent students: exclude student's assets if parents' combined AGI is less than $60K
-----Independent students with or without dependents: exclude assets if combined AGI of student & spouse is less than $60K

**Comment by kbottagaro** [comment]
Added note: Change 225% FPL to 175% FPL for independent students without children (i.e., Max Pell will show up in results for an independent student w/o children whose income is 175% 2022 FPL or lower).

**Comment by sydney-devine** [comment]
@CalebPena ^ making sure you see this.
