### ISSUE TITLE
Add WellPower to immediate needs 

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#495]
Add WellPower to immediate needs in MFB for Denver residents only. Show this in results if:

1. In Step 9, the user marks a need for help with "A challenge you or your child would like to talk about." AND
2. The user has a Denver zip code.

**Comment by sydney-devine** [comment]
@kbottagaro - @CalebPena says you can just add this in right now because Denver is already a function in the admin. :)

**Comment by kbottagaro** [comment]
@CalebPena Do I need to have an external name to add this?

**Comment by CalebPena** [comment]
@kbottagaro You can make the "external name" `well_power`, but it does not make a functional difference because the "external name" is just so that we can match translations across environments.

**Comment by kbottagaro** [comment]
Thank you. It's now been added, @sydney-devine and @CalebPena
