### ISSUE TITLE
Modify SNAP eligibility calculations if a user marks that a HH member is a student.

### ISSUE THREAD

**Issue by kbottagaro** [Gary-Community-Ventures/benefits-api#527]
Modify SNAP eligibility calculations if a user marks that a HH member is a student (i.e., student who attends college, university, or other post-secondary institution like job training).

Exclude the HH member who is a student from the HH for purposes of SNAP calculations UNLESS one or more of the following exemptions applies to that student:

- The student has a child under 6;
- The student is a single parent with a child under 12 (for MFB purposes, assume single if there is no “Spouse” or "Domestic Partner");
- The student is under 18 or 50+;
- The student has a disability that makes them unable to work (use only the "unable to work" disability category)

For users for whom we have excluded a student from SNAP calculations, add a popup message on SNAP results page: 
Special SNAP rules apply to students who attend college, university, or other post-secondary institutions like job training. Your SNAP results do not include the student(s) in your home. 

A student will be deemed to have a child for these purposes if they have a child or stepchild (but not foster child).

Background materials / sources are in this doc: https://docs.google.com/document/d/1wKbFiRECuhp3oue859njTdMWYT2vgU0-Qq4kaawUir4/edit?usp=sharing

**Comment by kbottagaro** [comment]
As part of this ticket, delete the period that appears at the end of the college student condition in step 5.

**Comment by sydney-devine** [comment]
@CalebPena adding in this piece for CDIG

<img width="1348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVl4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cc5929dd48378c16f687d9c399a42f1635c6a8f/image.png" alt="image.png" />
