### ISSUE TITLE
Add SNAP limited utility allowance calculation

### ISSUE THREAD

**Issue by Linda-Vu** [Gary-Community-Ventures/benefits-api#549]
The current calculation logic in the SNAP calculator does not account for when a household is eligible for a Limited Utility Allowance or LUA/BUA (Basic Utility Allowance).

The Snap Screener can be used for determining the SNAP eligibility and allowance amounts:
https://www.snapscreener.com/data
https://www.snapscreener.com/screener

Here are some tests done with the MFB Colorado screener with inconsistent results found compared to the snap screener:
https://docs.google.com/document/d/1Oc062F8xm-lhnb4DNTi-7Adbu-GKlp_LI8BeLVpMDeY/edit

Some context:
The relevant files that may need modification are the following:
- [pe/spm.py](https://github.com/Gary-Community-Ventures/benefits-api/blob/main/programs/programs/federal/pe/spm.py)
- [dependencies/spm.py](https://github.com/Gary-Community-Ventures/benefits-api/blob/main/programs/programs/policyengine/calculators/dependencies/spm.py)

With the current implementation a household technically should become eligible for LUA if it enters 'Other Utilities' and a 'Telephone' household expenses but not 'Heating' or 'Cooling' expenses as it seems that the current `Snap` class includes a `HasPhoneExpenseDependency` and another `ElectricityExpenseDependency` (the `ElectricityExpenseDependency` corresponds to the 'Other Utilities' household expense input in the screener). So this might be more of a bug than an implementation problem.

**Comment by CalebPena** [comment]
This won't affect Colorado starting in October because there is a new rule being passed that will make everyone eligible for the SUA, but here is how I would go about solving this.

1. Find the PE variables that affect the LUA.
2. Find the corresponding MFB fields to the PE variables.
3. Add the new PE variables by updating the dependencies on the NC SNAP.
